указываем версию схемы БД как 6 в InTimeOpenHelper, так как код начал обращаться к старому коду почему-то и возникал конфликт между версиями БД
2026-05-17 22:32:08.396  6298-6298  AndroidRuntime          com.vpe_soft.intime.intime.dev       E  FATAL EXCEPTION: main
                                                                                                    Process: com.vpe_soft.intime.intime.dev, PID: 6298
                                                                                                    java.lang.RuntimeException: Unable to start receiver com.vpe_soft.intime.intime.receiver.BootReceiver: android.database.sqlite.SQLiteException: Can't downgrade database from version 6 to 5
                                                                                                    	at android.app.ActivityThread.handleReceiver(ActivityThread.java:4781)
                                                                                                    	at android.app.ActivityThread.-$$Nest$mhandleReceiver(Unknown Source:0)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2436)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:107)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:232)
                                                                                                    	at android.os.Looper.loop(Looper.java:317)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8705)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:886)
                                                                                                    Caused by: android.database.sqlite.SQLiteException: Can't downgrade database from version 6 to 5
                                                                                                    	at android.database.sqlite.SQLiteOpenHelper.onDowngrade(SQLiteOpenHelper.java:547)